/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const authConfig = {
  aws_project_region: "us-east-1",
  aws_cognito_identity_pool_id:
    "us-east-1:022fe8ec-df61-465e-815e-a93f645afd87",
  aws_cognito_region: "us-east-1",
  aws_user_pools_id: "us-east-1_bEKRzMrYd",
  aws_user_pools_web_client_id: "73t5dtv94km7gqhvpdfel8d25b",
  oauth: {},
  aws_cognito_username_attributes: ["EMAIL"],
  aws_cognito_social_providers: [],
  aws_cognito_signup_attributes: [
    "GIVEN_NAME",
    "FAMILY_NAME",
    "PHONE_NUMBER",
    "EMAIL",
  ],
  aws_cognito_mfa_configuration: "OFF",
  aws_cognito_mfa_types: ["SMS"],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [],
  },
  aws_cognito_verification_mechanisms: ["EMAIL"],
};

export default authConfig;
